name: Deploy static site to Yandex Object Storage

on:
  push:
    branches: [ "main", "wip" ]
  workflow_dispatch:
    inputs:
      target:
        description: "Куда деплоим?"
        type: choice
        required: true
        options: [ "prod", "wip" ]
        default: "wip"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ru-central1
      S3_ENDPOINT: https://storage.yandexcloud.net
      S3_BUCKET: ${{ vars.S3_BUCKET }}   # имя бакета из Variables
      # вычисляем префикс
      PREFIX: ${{ github.ref_name == 'main' && '' || (github.ref_name == 'wip' && 'wip/' || '') }}
    steps:
      - uses: actions/checkout@v4

      # Согласовываем manual target с веткой (fail-fast, если не совпало)
      - name: Validate manual target (only on dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          target='${{ inputs.target }}'
          ref='${{ github.ref_name }}'
          if [ "$target" = "prod" ] && [ "$ref" != "main" ]; then
            echo "::error ::Manual target=prod, но ветка не main"; exit 1
          fi
          if [ "$target" = "wip" ] && [ "$ref" = "main" ]; then
            echo "::error ::Manual target=wip, но ветка main"; exit 1
          fi

      - name: Build (генерация build.js и т.п.)
        run: |
          # ваш билд тут
          echo "build..."

      - name: Sync static
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          DEST="s3://${S3_BUCKET}/${PREFIX}"
          echo "Sync to $DEST"
          aws s3 sync ./general_preview "$DEST" \
            --delete --acl public-read --endpoint-url "${S3_ENDPOINT}"

      - name: Set no-cache for build.js
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          DEST="s3://${S3_BUCKET}/${PREFIX}build.js"
          aws s3 cp general_preview/build.js "$DEST" \
            --cache-control "max-age=0" --metadata-directive REPLACE \
            --acl public-read --endpoint-url "${S3_ENDPOINT}"
ы