name: Deploy static site to Yandex Object Storage

on:
  push:
    branches: [ "main", "wip" ]   # деплоим из main и wip
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ru-central1
      AWS_ENDPOINT_URL: https://storage.yandexcloud.net
      S3_BUCKET: ${{ vars.S3_BUCKET }}   # задай в Repository → Settings → Variables → S3_BUCKET
    steps:
      - uses: actions/checkout@v4

      # Если у тебя есть сборка — добавь тут (npm ci && npm run build и т.п.)
      # Ниже деплоим содержимое ./general_preview, как у тебя было раньше.

      - name: Decide deploy prefix (root for main, /wip/ for wip)
        id: path
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "prefix=" >> $GITHUB_OUTPUT           # корень бакета
          else
            echo "prefix=wip/" >> $GITHUB_OUTPUT       # папка wip/
          fi
          echo "Deploying to s3://${{ env.S3_BUCKET }}/${{ steps.path.outputs.prefix }}"

      - name: Upload all files except index.html (long cache ok)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./general_preview "s3://${S3_BUCKET}/${{ steps.path.outputs.prefix }}"             --endpoint-url "$AWS_ENDPOINT_URL"             --delete             --exclude "index.html"             --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html last (no cache)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          if [ -f ./general_preview/index.html ]; then
            aws s3 cp ./general_preview/index.html "s3://${S3_BUCKET}/${{ steps.path.outputs.prefix }}index.html"               --endpoint-url "$AWS_ENDPOINT_URL"               --cache-control "no-store"               --content-type "text/html"               --metadata-directive REPLACE
          fi

      - name: (Optional) Upload build.js with no cache too
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          if [ -f ./general_preview/build.js ]; then
            aws s3 cp ./general_preview/build.js "s3://${S3_BUCKET}/${{ steps.path.outputs.prefix }}build.js"               --endpoint-url "$AWS_ENDPOINT_URL"               --cache-control "no-store"               --content-type "application/javascript"               --metadata-directive REPLACE
          fi
