name: Deploy PROD (main → bucket root)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ru-central1
      AWS_EC2_METADATA_DISABLED: "true"
      S3_ENDPOINT: https://storage.yandexcloud.net
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      PREFIX: ""   # корень бакета

    steps:
      - uses: actions/checkout@v4

      - name: Build (создай general_preview/build.js и статик)
        run: |
          set -euxo pipefail
          # пример: npm ci && npm run build
          ls -la .
          ls -la general_preview || true

      - name: Sync static to PROD root
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          set -euxo pipefail
          DEST="s3://${S3_BUCKET}/${PREFIX}"
          aws --version
          aws s3 sync ./general_preview "$DEST" \
            --delete --acl public-read \
            --no-progress --only-show-errors \
            --endpoint-url "${S3_ENDPOINT}"

      - name: Set no-cache for build.js (if exists)
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          set -euxo pipefail
          if [ ! -f general_preview/build.js ]; then
            echo "::warning ::general_preview/build.js не найден — пропускаю no-cache"
            exit 0
          fi
          DEST="s3://${S3_BUCKET}/${PREFIX}build.js"
          aws s3 cp general_preview/build.js "$DEST" \
            --cache-control "max-age=0" \
            --metadata-directive REPLACE \
            --acl public-read \
            --no-progress --only-show-errors \
            --endpoint-url "${S3_ENDPOINT}"

      - name: Verify build.js on bucket
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          set -euxo pipefail
          aws s3 ls "s3://${S3_BUCKET}/build.js" --endpoint-url "${S3_ENDPOINT}" || \
            echo "::warning ::не вижу build.js (возможно, сборка его не создала)"
