name: Deploy static site to Yandex Object Storage

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # AWS CLI уже предустановлен на runner'ах GitHub
      - name: Sync to Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          aws s3 sync ./general_preview s3://${{ vars.S3_BUCKET }} \
            --delete \
            --acl public-read \
            --endpoint-url https://storage.yandexcloud.net
